spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:url_db
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: create-drop
